// frontend/src/components/ui/Button.tsx
import { ButtonHTMLAttributes, PropsWithChildren } from 'react';

type ButtonProps = PropsWithChildren<
  ButtonHTMLAttributes<HTMLButtonElement> & {
    variant?: 'primary' | 'secondary' | 'tertiary';
  }
>;

export function Button({ children, className = '', variant = 'primary', ...props }: ButtonProps) {
  const variants = {
    primary:
      'bg-[var(--color-brand-primary)] text-[var(--color-text-inverse)] shadow-[var(--shadow-button)] hover:bg-[var(--color-brand-primary-hover)]',
    secondary:
      'border border-[var(--color-border-strong)] bg-[var(--color-surface-raised)] text-[var(--color-text-primary)] hover:bg-[var(--color-surface-tinted)]',
    tertiary:
      'bg-transparent text-[var(--color-brand-primary)] hover:bg-[var(--color-brand-primary-soft)]',
  };

  return (
    <button
      className={`inline-flex h-12 items-center justify-center rounded-[14px] px-5 text-sm font-semibold transition duration-180 ease-[cubic-bezier(0.22,1,0.36,1)] focus:outline-none focus:ring-4 focus:ring-[var(--color-focus-soft)] disabled:cursor-not-allowed disabled:opacity-60 ${variants[variant]} ${className}`}
      {...props}
    >
      {children}
    </button>
  );
}

// frontend-vue/src/components/Button.vue
<script setup>
const props = defineProps({
  variant: { type: String, default: 'primary' },
  size: { type: String, default: 'md' },
})

const variants = {
  primary: 'bg-brand-primary text-text-inverse hover:bg-brand-primary-hover active:bg-brand-primary-active',
  secondary: 'bg-surface-raised border border-border-strong text-text-primary hover:bg-surface-tinted',
  tertiary: 'text-brand-primary hover:bg-brand-primary-soft',
  danger: 'bg-danger text-text-inverse hover:bg-red-700',
}

const sizes = {
  sm: 'px-3 py-2 text-body-sm',
  md: 'px-4 py-3 text-body-md',
  lg: 'px-6 py-4 text-body-md',
}
</script>

<template>
  <button
    :class="[
      'font-semibold rounded transition-colors duration-180 focus:outline-none focus:ring-2 focus:ring-focus',
      variants[props.variant],
      sizes[props.size],
    ]"
  >
    <slot />
  </button>
</template>
