// frontend-vue/src/components/InputField.vue
<script setup>
defineProps({
  label: { type: String, default: '' },
  placeholder: { type: String, default: '' },
  type: { type: String, default: 'text' },
  modelValue: { type: String, default: '' },
})

const emit = defineEmits(['update:modelValue'])
</script>

<template>
  <div class="mb-4">
    <label v-if="label" class="label text-text-primary block mb-2">{{ label }}</label>
    <input
      :type="type"
      :placeholder="placeholder"
      :value="modelValue"
      class="w-full px-4 py-3 text-body-md rounded-sm border border-border-subtle bg-surface-raised text-text-primary placeholder-text-muted focus:outline-none focus:border-brand-primary focus:ring-2 focus:ring-focus transition-colors"
      @input="emit('update:modelValue', $event.target.value)"
    />
  </div>
</template>

// frontend/src/components/ui/InputField.tsx
import { InputHTMLAttributes } from 'react';

type InputFieldProps = InputHTMLAttributes<HTMLInputElement> & {
  label: string;
  error?: string;
};

export function InputField({ label, error, className = '', ...props }: InputFieldProps) {
  return (
    <label className="flex flex-col gap-2">
      <span className="text-xs font-semibold uppercase tracking-[0.18em] text-[var(--color-text-muted)]">{label}</span>
      <input
        className={`h-12 rounded-[12px] border border-[var(--color-border-subtle)] bg-[var(--color-surface)] px-4 text-base text-[var(--color-text-primary)] outline-none transition focus:border-[var(--color-brand-primary)] focus:ring-4 focus:ring-[var(--color-focus-soft)] ${className}`}
        {...props}
      />
      {error ? <span className="text-sm text-[var(--color-danger)]">{error}</span> : null}
    </label>
  );
}
